ethereum_smartcontract.contract.*:
  type: config_entity
  label: 'Smart Contract config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    contract_src:
      type: string
      label: 'Contract Source file'
    contract_js:
      type: string
      label: 'Compiled contract Javascript file.'
